language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update
  - pip install telebot
  - pip install flask
  - pip install pymongo
  - pip install aiohttp
  - pip install psutil
  - pip3 install python-telegram-bot

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp

script:
  - chmod +x *   # Saari files ko executable banao
  - chmod +x Sahil  # Ensure BGMI executable permissions
  - echo "Starting Sahil.py..."
  - travis_wait 120 python3 Sahil.py  # Sahil.py ko run karo and wait karke 120 minutes tak chale
  - echo "Starting BGMI..."
  - travis_wait 120 ./bgmi  # Aapki binary ko run karega aur 120 minutes tak wait karega
